name: Build and Deploy

run-name: Build and Deploy to OpenShift

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag à déployer'
        required: false
        default: ''

env:
  REGISTRY: harbor.kakor.ovh/ipim2il/groupe-2

jobs:
  build-and-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Login to Harbor
      uses: docker/login-action@v4
      with:
        registry: harbor.kakor.ovh
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install OpenShift CLI
      run: |
        curl -L -o /tmp/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar xz -C /usr/local/bin -f /tmp/oc.tar.gz
        chmod +x /usr/local/bin/oc
        oc version

    - name: Login to OpenShift
      run: |
        oc login --token=${{ secrets.OPENSHIFT_TOKEN }} \
                 --server=${{ secrets.OPENSHIFT_SERVER }} \
                 --insecure-skip-tls-verify

    - name: Define image tag
      id: vars
      run: |
        if [ "${{ github.event.inputs.image_tag }}" != "" ]; then
          echo "IMAGE_TAG=${{ github.event.inputs.image_tag }}" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}" >> $GITHUB_ENV
        fi

    - name: Apply Kubernetes resources
      run: |
        oc apply -f flask-deployment.yaml -n project-gp-2

    - name: Update image (force rollout)
      run: |
        oc set image deployment/lucas-deployment \
          flask-container=${{ env.REGISTRY }}:${IMAGE_TAG} \
          -n project-gp-2

    - name: Verify deployment
      run: |
        oc rollout status deployment/lucas-deployment -n project-gp-2