name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag à déployer'
        required: false
        default: 'latest'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.kakor.ovh
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: harbor.kakor.ovh/ipim2il/groupe-2:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OpenShift CLI
      run: |
        # Download and install OpenShift CLI
        curl -L -o /tmp/oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
        tar xz -C /usr/local/bin -f /tmp/oc.tar.gz
        chmod +x /usr/local/bin/oc
        oc version

    - name: Login to OpenShift
      run: |
        oc login --token=${{ secrets.OPENSHIFT_TOKEN }} --server=${{ secrets.OPENSHIFT_SERVER }} --insecure-skip-tls-verify

    - name: Deploy to OpenShift
      run: |
        oc apply -f flask-deployment.yaml

    - name: Verify deployment
      run: |
        oc rollout status deployment/flask-app -n default
